#include <stdio.h>
#include <stdlib.h>
#include "j4emlinha_gui.h"
/*
Autor: Gustavo Almeida
Local: Pojuca - Ba
Data: 22/06/2013
Especificação dos métodos da biblioteca gráfica do jogo.
*/


void criatelas(int forcado){
    FILE *a = fopen_s("guiarqs\\Telas","rb", stdout);
    if(a == NULL || forcado == 1){
        a = fopen_s("guiarqs\\Telas","wb", stdout);
        tptransf dd;
    //-----------------------------------------Criação do binário com o visual do jogo--------------------------------------------------------------

        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                                             Autor: Gustavo Almeida";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                    _____";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                  //     |                                                                           \\";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                 //  /|  |                                __                  __                   \\ \\\\";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                //  / |  |    ______    __ ___ ___       || |   _   __ ___   || |___      ___ __      \\ \\ \\";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "               //  /__|  |   ||  __ `\\ || '_  ' _  \\     || | ((_) || '_  \\  ||  __ `\\  //  _`  |   \\ \\  __";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "               ||_____   |   || |_||_| || Y Y| | Y| |    || | || | || Y Y| | || | || | ||  /\\\\  |  \\   //  \\ ";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                     ||  |   || |__    || | || | || |    || | || | || | || | || | || | ||  \\//  |     || () |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                     ||__|   ||____|   ||_| ||_| ||_|    ||_| ||_| ||_| ||_| ||_| ||_|  \\\\___/|_|      \\\\__/";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 1;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "\n";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                                                        Menu";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [1]Contra o computador";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [2]Contra outro jogador ";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [3]Regras do jogo";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [4]Recordes";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [5]Sair";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 2;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                                    Digite a opcao ou escolha com as setas e apenter enter";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                                                      Nivel";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [1]Ridiculo";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [2]Facil ";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [3]Normal";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [4]Dificil";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               [5]Escabroso";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                                    Digite a opcao ou escolha com as setas e apenter enter";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 3;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 4;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 4;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                                                      Nome do Jogador";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 4;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 4;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               ->";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 5;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 5;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                                                      Nome do Jogador 1";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 5;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               ->";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 6;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 6;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "                                                      Nome do Jogador 2";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 6;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "                                               ->";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "Regras do jogo";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "- Cada jogador escolhe uma coluna para colocar o disco";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "- O disco desce ate a eltima posicao livre da coluna";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "- O primeiro que fizer uma linha com quantro discos ganha";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "- Pode fazer linha na horizontal, vertical e diagonal";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "- No jogo contra o computador:";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 7;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "     Sua pontuacao sera 10x a quantidade de discos colocados em linha de 3";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "Recordes";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = " __________________________________________________________";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||               Partidas contra o computador              |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||---------------------------------------------------------|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||Posicao |       Nome          |no partidas|    Potuacao  |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   1    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   2    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   3    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   4    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   5    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   6    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   7    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   8    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   9    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   10   |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||_________________________________________________________|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|//////////////////////////////////////////////////////////";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = " __________________________________________________________";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||              Partidas contra outro jogador              |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||---------------------------------------------------------|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||Posicao |       Nome          |    Placar    |  Empates  |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   1    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   2    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   3    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   4    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   5    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   6    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   7    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   8    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   9    |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 1;
        dd.sd = "||   10   |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 2;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 1;
        dd.wins = 3;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||_________________________________________________________|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|//////////////////////////////////////////////////////////";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 2;
        dd.wins = 1;
        dd.sd = "                     ";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 2;
        dd.wins = 2;
        dd.sd = "              ";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 8;
        dd.seins = 2;
        dd.wins = 3;
        dd.sd = "           ";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = " __________________________________________";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||  1  |  2  |  3  |  4  |  5  |  6  |  7  |";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||-----|-----|-----|-----|-----|-----|-----|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "||";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||-----|-----|-----|-----|-----|-----|-----|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "||";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||-----|-----|-----|-----|-----|-----|-----|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "||";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||-----|-----|-----|-----|-----|-----|-----|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "||";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||-----|-----|-----|-----|-----|-----|-----|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "||";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||-----|-----|-----|-----|-----|-----|-----|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "||";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 1;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||-----|-----|-----|-----|-----|-----|-----|";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 0;
        dd.wins = 0;
        dd.sd = "||/////////////////////////////////////////";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 2;
        dd.wins = 0;
        dd.sd = "     ";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 2;
        dd.wins = 1;
        dd.sd = " (x) ";
        fwrite(&dd,sizeof(dd),1,a);
        dd.nt = 9;
        dd.seins = 2;
        dd.wins = 2;
        dd.sd = " (o) ";
        fwrite(&dd,sizeof(dd),1,a);

    //---------------------------------------------------------------------------------------------------------------------

    }
    fclose(a);

}

void tamanhotela(int largura,int altura){
    HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
    SMALL_RECT windowSize ;
    windowSize.Top=1;
    windowSize.Left=4;
    windowSize.Bottom = altura - 1;
    windowSize.Right = largura - 1;
    COORD c;
    c.X = largura;
    c.Y = altura;
    SetConsoleWindowInfo(hConsole, TRUE, &windowSize);
    SetConsoleScreenBufferSize(hConsole,c);
}

void vertela(int ntela){
    if(ntela <= 9){
        int tlatual = 0;
        tptransf trlinha;
        FILE *a = fopen_s("guiarqs\\Telas","rb", stdout);
        while(tlatual != ntela){
            fread(&trlinha,sizeof(trlinha),1,a);
            tlatual = trlinha.nt;
        }
        while(tlatual == ntela && !feof(a)){
            printf(trlinha.sd);
            if(trlinha.seins == 0){
                printf("\n");
            }
            fread(&trlinha,sizeof(trlinha),1,a);
            tlatual = trlinha.nt;
        }
        fclose(a);
    }
}

int menudinamico(int ntmenu){
    int tlatual = 0,nitens;
    tptransf trlinha;
    FILE *a = fopen_s("guiarqs\\Telas","rb", stdout);
    fpos_t posic;
    do{
        fread(&trlinha,sizeof(trlinha),1,a);
        tlatual = trlinha.nt;
    }while(tlatual != ntmenu && !feof(a));
    fgetpos(a,&posic);
    int ite = 1,tecla;
        menuin:

        if(ntmenu == 2){
            nitens = 5;
        }else if(ntmenu == 3){
            nitens = 5;
        }
        system("cls");
        vertela(1);
        int positem = 1;
        fsetpos(a,&posic);
        fread(&trlinha,sizeof(trlinha),1,a);
        tlatual = trlinha.nt;
        while(tlatual == ntmenu && !feof(a)){
            printf(trlinha.sd);
            if(trlinha.seins == 0){
                printf("\n");
            }else{
                if(positem == ite){
                    positem++;
                    printf(" <<|\n");
                }else{
                    positem++;
                    printf("\n");
                }
            }
            fread(&trlinha,sizeof(trlinha),1,a);
            tlatual = trlinha.nt;
        }
        tecla = _getch();
        if(tecla== 72){
            ite--;
            if(ite < 1){
                ite = nitens;
            }
            goto menuin;
        }else if(tecla == 80){
            ite++;
            if(ite > nitens){
                ite = 1;
            }
            goto menuin;
        }else if(tecla == 75){
            menudinamico(2);
        }else if(tecla == 13){
            fclose(a);
            return ite;
        }else if(tecla >= 49 && tecla <= (48+nitens)){
            fclose(a);
            return tecla - 48;
        }else{
            goto menuin;
        }
}

void carregandotela(int seg){
    int ct,ct2,ct3;
    float pct = 0;
    char roda[8] = "|/-\\|/-\\";
    for(ct = 0;ct < seg;ct++){
        for(ct2 = 0; ct2 < 8;ct2++){
            system("cls");
            vertela(1);
            pct+=1.0/seg/8*100;
            printf("\n\t\t\t\t\t Carregando... \n\t\t\t\t\t%c",roda[ct2]);
            for(ct3 = 0;ct3 < pct/5;ct3++){
                printf("=");
            }
            printf("| %.1f%%|",pct);
            Sleep(1000/8);
        }
    }
}

int atua_tljogo(int mesa[6][7],int jogseta){
    int tlatual = 0,cx = 0,cy = 0,posicaoinicial = 0;
    tptransf trlinha;
    lin_carac discos[3];
    FILE *a = fopen_s("guiarqs\\Telas","rb", stdout);
    fpos_t posic;
    do{
        fread(&trlinha,sizeof(trlinha),1,a);
        tlatual = trlinha.nt;
        if(trlinha.seins==2){
            discos[trlinha.wins].caract = trlinha.sd;
        }
        if(tlatual == 9 && posicaoinicial == 0){
            fgetpos(a,&posic);
            posicaoinicial = 1;
        }
    }while(!feof(a));
    int tecla,ct,colatual = 1;
        topoframe:

        system("cls");
        for(ct = 1;ct < colatual;ct++){
            printf(" %s",discos[0].caract);
        }
        printf("  %s\n",discos[jogseta].caract);
        fsetpos(a,&posic);
        fread(&trlinha,sizeof(trlinha),1,a);
        tlatual = trlinha.nt;
        while(tlatual == 9 && trlinha.seins != 2){
            printf(trlinha.sd);
            if(trlinha.seins == 0){
                printf("\n");
            }else{
                printf("%s",discos[mesa[cx][cy]].caract);
                cy++;
                if(cy>6){
                    cy = 0;
                    cx++;
                }
            }
            fread(&trlinha,sizeof(trlinha),1,a);
            tlatual = trlinha.nt;
        }
        cx = 0;
        tecla = _getch();
        if(tecla== 75){
            colatual--;
            if(colatual < 1){
                colatual = 7;
            }
            goto topoframe;
        }else if(tecla == 77){
            colatual++;
            if(colatual > 7){
                colatual = 1;
            }
            goto topoframe;
        }else if(tecla == 13){
            fclose(a);
            return colatual-1;
        }else if(tecla >= 49 && tecla <= (48+7)){
            colatual = tecla - 48;
            goto topoframe;
        }else{
            goto topoframe;
        }
}

